import simpleGit from 'simple-git'
import { podExec } from '#platform/k8s'
import { buildWorktreeRegistration, proxyClient } from '#runtime/k8s/egress'
import { repoDir } from '@yaac/shared/project-paths'
import {
  resolveProjectConfig,
  resolveEphemeralModulesPaths,
} from '#features/projects'
import { loadToolAuthEntry } from '@yaac/shared/tool-auth'
import { shellEscape } from '#platform/shell'
import {
  resolveInitWindows,
  buildAgentCmd,
  verifyAgentWindowAlive,
  initWindowCommand,
  TMUX,
} from '#runtime/agents'
import { withUpstreamConfigLock } from './create'
import type { AgentTool, YaacConfig } from '@yaac/shared/types'
import type { PiProvider } from '@yaac/shared/tool-providers'

/**
 * Swap a prewarmed spare's booted agent for a different tool at claim time.
 * Spares are provisioned tool-agnostically (mounts, env placeholders, and
 * per-tool config cover every tool), so only three things are keyed to the
 * booted tool: the proxy registration (drives credential injection), the
 * agent tmux window's name, and the process running in it. Re-registers the
 * proxy worktree, then renames + respawns the agent window and verifies the
 * respawned agent survived. The pod's tool label flips in the claim's
 * commit call. Throws on failure — the caller must treat the spare as
 * tainted (registration, window name, and label may disagree) and reap it.
 *
 * The in-pod commands ride the stream relay, so the caller must have gated
 * on `waitForStreamd` (the claim path does, before its first mutation).
 */
export async function retoolSpare(
  spare: { jobName: string; worktreeId: string; projectSlug: string; tool: string },
  tool: AgentTool,
  /** Model for the respawned agent (see buildAgentCmd). Also the reason a
   *  claim may retool a spare to its *own* tool: the booted agent has no
   *  model flag, so a model override forces this respawn. */
  model?: string,
): Promise<void> {
  const config: YaacConfig = await resolveProjectConfig(spare.projectSlug) ?? {}
  const remoteUrl = (await simpleGit(repoDir(spare.projectSlug)).remote(['get-url', 'origin']))?.trim() ?? ''
  // pi's launch command embeds its provider's default model, so a retool to pi
  // needs the stored provider (from the single pi.json credential).
  const piProvider = tool === 'pi' ? (await loadToolAuthEntry('pi'))?.piProvider : undefined
  await proxyClient.registerWorktree(
    spare.worktreeId,
    buildWorktreeRegistration({ config, remoteUrl, tool, projectSlug: spare.projectSlug }),
  )
  // Written to tolerate having already run, so the dial retries stay on:
  // by the time a claim gets here any throw reaps the spare, and a blip on
  // the shared port-forward is far likelier than the rename failing for
  // real. The fallback passes only when the window already carries the new
  // name — a genuine failure still exits nonzero, with tmux's own stderr
  // (deliberately not silenced) explaining it.
  await podExec(
    spare.jobName,
    `${TMUX} rename-window -t yaac:${spare.tool} ${tool}`
    + ` || ${TMUX} list-windows -t =yaac -F '#{window_name}' | grep -qxF ${tool}`,
  )
  await podExec(
    spare.jobName,
    `${TMUX} respawn-window -k -t yaac:${tool} '${buildAgentCmd(tool, spare.worktreeId, false, piProvider, model)}'`,
  )
  await verifyAgentWindowAlive(spare.jobName, tool)
}

/** The in-pod commands that re-point a prewarmed spare's worktree at a
 *  different reference branch. Assembled by `buildRebranchPrep` (pure, so
 *  the command set is unit-testable) and executed by `rebranchSpare`. */
export interface RebranchPrepCommands {
  /** Moves `agent/<id>` to the resolved SHA and drops non-ignored strays.
   *  Deliberately `clean -fd`, not `-x`: ephemeral-modules mounts
   *  (node_modules) and cache volumes are live mount points whose contents
   *  a `-x` clean would empty; ignored build artifacts that survive are
   *  regenerated by the respawned init windows. */
  resetExec: string
  /** Rewrites `branch.agent/<id>.merge` in the shared /repo/.git/config —
   *  must run under `withUpstreamConfigLock`. */
  upstreamExec: string
  /** Kill + re-create every init window (they ran against the old
   *  checkout), then respawn the agent window when requested — the spare's
   *  booted agent read the old checkout at startup and holds no
   *  conversation yet, so a respawn loses nothing. */
  windowExecs: string[]
}

/**
 * Workspace-relative paths that are live mount points inside the pod —
 * ephemeral-modules redirects (`/workspace/node_modules` by default), plus
 * any cacheVolumes / bindMounts targeting a path under /workspace. `git
 * clean` must skip them: in a repo that doesn't gitignore them they're
 * untracked directories, and removing a mount point fails (EBUSY), which
 * would taint every re-branch.
 */
function workspaceMountPaths(config: YaacConfig): string[] {
  const underWorkspace = (p: string): string | null =>
    p.startsWith('/workspace/') ? p.slice('/workspace/'.length) : null
  return [
    ...resolveEphemeralModulesPaths(config),
    ...Object.values(config.cacheVolumes ?? {}).map(underWorkspace),
    ...(config.bindMounts ?? []).map((b) => underWorkspace(b.containerPath)),
  ].filter((p): p is string => p !== null && p.length > 0)
}

export function buildRebranchPrep(params: {
  branch: string
  /** Resolved `refs/remotes/origin/<branch>` SHA. The reset uses the SHA,
   *  not the ref name: host-fetch writes reach pods through the virtiofs
   *  cache with a possible seconds-stale window for replaced files
   *  (packed-refs), while new object files are new dentries and safe. */
  sha: string
  config: YaacConfig
  worktreeId: string
  /** Agent window to respawn, or null when a retool follows (its own
   *  respawn supersedes this one). */
  respawnTool: AgentTool | null
  /** pi only — provider for the respawn's `pi --model` (see buildAgentCmd). */
  piProvider?: PiProvider
}): RebranchPrepCommands {
  const { branch, sha, config, worktreeId, respawnTool, piProvider } = params
  const windowExecs: string[] = []
  for (const win of resolveInitWindows(config)) {
    // Kill and re-create in ONE exec, so re-running the pair is a no-op.
    // Split across two execs it is not: tmux allows duplicate window
    // names, so a `new-window` that ran but whose reply was lost leaves a
    // second window of the same name behind, racing two copies of the init
    // command over one worktree (two concurrent `pnpm install`s), and a
    // later kill-window removes only one of them. Paired, a re-run kills
    // whatever the lost attempt created before making its own. The kill
    // tolerates a missing window — hidePane windows are gone once their
    // command finishes — and `;` keeps its status out of the result.
    windowExecs.push(
      `${TMUX} kill-window -t yaac:${win.name} 2>/dev/null; ${initWindowCommand(win)}`,
    )
  }
  if (respawnTool) {
    windowExecs.push(
      `${TMUX} respawn-window -k -t yaac:${respawnTool} '${buildAgentCmd(respawnTool, worktreeId, false, piProvider)}'`,
    )
  }
  const cleanExcludes = workspaceMountPaths(config)
    .map((p) => ` -e '${shellEscape(p)}'`)
    .join('')
  return {
    resetExec: `sh -c "git -C /workspace reset --hard ${sha} && git -C /workspace clean -fd${cleanExcludes}"`,
    upstreamExec: `git -C /workspace branch --set-upstream-to 'origin/${shellEscape(branch)}'`,
    windowExecs,
  }
}

/**
 * Re-point a prewarmed spare's baked worktree at a different reference
 * branch at claim time — the branch analogue of `retoolSpare`, so any spare
 * serves any branch. The caller resolves the SHA (host-side, post-fetch) and
 * validates the branch exists BEFORE calling; from the first exec on, a
 * failure means the spare is tainted (worktree, upstream, and windows may
 * disagree) and the caller must reap it.
 *
 * Like `retoolSpare`, the in-pod commands ride the stream relay, so the
 * caller must have gated on `waitForStreamd` first. Each is written to be
 * a no-op when re-run (see `buildRebranchPrep`), so they keep the default
 * dial retries.
 */
export async function rebranchSpare(
  spare: { jobName: string; worktreeId: string; projectSlug: string; tool: string },
  branch: string,
  sha: string,
  respawnAgent: boolean,
): Promise<void> {
  const config: YaacConfig = await resolveProjectConfig(spare.projectSlug) ?? {}
  const piProvider = respawnAgent && spare.tool === 'pi'
    ? (await loadToolAuthEntry('pi'))?.piProvider
    : undefined
  const prep = buildRebranchPrep({
    branch,
    sha,
    config,
    worktreeId: spare.worktreeId,
    respawnTool: respawnAgent ? spare.tool as AgentTool : null,
    piProvider,
  })
  // The reset+clean walks the whole worktree, so it gets a wider deadline
  // than the relay's 30s default (kubectl exec ran it unbounded). Only the
  // run phase widens — podExec caps the dial separately — and a read
  // timeout past that is not retried, so a still-running git can't be
  // raced by a second one over the same index.lock.
  await podExec(spare.jobName, prep.resetExec, { timeout: 120_000 })
  await withUpstreamConfigLock(spare.projectSlug, async () => {
    await podExec(spare.jobName, prep.upstreamExec)
  })
  for (const cmd of prep.windowExecs) await podExec(spare.jobName, cmd)
  if (respawnAgent) await verifyAgentWindowAlive(spare.jobName, spare.tool as AgentTool)
}
