FROM yaac-base

COPY .nvmrc /tmp/.nvmrc

ENV NVM_DIR="/home/yaac/.nvm"

RUN curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
    bash -c '. "$NVM_DIR/nvm.sh" && cd /tmp && nvm install && corepack enable && corepack prepare pnpm@10.7.0 --activate' && \
    ln -s "$NVM_DIR/versions/node/v$(cat /tmp/.nvmrc)" "$NVM_DIR/current"

ENV PATH="/home/yaac/.nvm/current/bin:$PATH"
