import { randomUUID } from 'node:crypto'
import { Hono } from 'hono'
import { zv } from '#routes/validator'
import { z } from 'zod'
import {
  allowWorktreeHost,
  dismissWorktreePort,
  forwardWorktreePort,
  getAgentSessionTranscript,
  getWorktreeBlockedHosts,
  getWorktreeChanges,
  getWorktreeDetail,
  getWorktreePrompt,
  listActiveWorktrees,
  listStoppedWorktrees,
  listWorktreeGroups,
  registerProvisioning,
  removeProvisioning,
  resolveGroup,
  resolveSessionInProject,
  resolveWorktreeContainer,
  resolveWorktreeRecord,
  restartWorktree,
  runMamaCommand,
  toAgentSessionEntry,
  type WorktreeCreateOptions,
} from '#domain/worktrees'
import {
  createWorktree,
  resolvePermissionMode,
  stopWorktree,
  tryClaimPrewarmed,
} from '#domain/worktrees'
import { typeInitialPrompt } from '#runtime/agents'
import { createShellWindow, killWindowTerminal, listWorktreeTerminals } from '#runtime/terminals'
import {
  createWorktreeGroup,
  deleteWorktreeGroup,
  findWorktreeByMamaToken,
  findWorktreeRow,
  listWorktreeAgentSessions,
  recordAllDeathsSeen,
  recordDeathSeen,
  renameWorktreeGroup,
  setWorktreeGroup,
  setWorktreeGroupPinned,
  setWorktreeTitle,
} from '#db'
import { getDefaultTool, recordProjectPermissionMode } from '#db'
import { streamProvisioned } from '#routes/provisioned-stream'
import { requireDriverFeature } from '#http'
import { worktreeDriver } from '#drivers/driver'
import { ServerError } from '@yaac/shared/errors'
// A group name is stored under `normalizeTitle`, which caps at this — so it
// is also what every route may ACCEPT. A larger bound would take a name in,
// truncate it on the way to the table, and let two distinct long names
// sharing a prefix resolve to one group.
import { MAX_TITLE_LENGTH } from '@yaac/shared/titles'
import { MODEL_RE, PERMISSION_MODES, SUPPORTED_PERMISSION_MODES } from '@yaac/shared/types'

export const worktreeApp = new Hono()
  .get(
    '/list',
    zv('query', z.object({ project: z.string().optional() })),
    async (c) => {
      const { project } = c.req.valid('query')
      return c.json(await listActiveWorktrees(project || undefined))
    },
  )
  .get(
    '/list-stopped',
    zv('query', z.object({
      project: z.string().optional(),
      limit: z.coerce.number().int().positive().optional(),
    })),
    async (c) => {
      const { project, limit } = c.req.valid('query')
      return c.json(await listStoppedWorktrees(project || undefined, limit))
    },
  )
  .post(
    '/create',
    zv('json', z.object({
      project: z.string().min(1),
      // Pre-generated by the webapp so the provisioning row is selectable and
      // reload-matchable before any round-trip; the CLI omits it and the
      // server mints one.
      worktreeId: z.string().uuid().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      // Which protocol drives the agent. `acp` needs a tool with an adapter
      // in the image; createWorktree rejects the combination before it
      // provisions anything.
      mode: z.enum(['tui', 'acp']).optional(),
      // Let the runtime install the agent's CLI rather than refusing a
      // create naming one it hasn't got — the caller carrying a user who
      // said yes to that (the `MISSING_TOOL` retry, `--install-missing`).
      // Only a runtime with no image to supply tools acts on it.
      installMissingTool: z.boolean().optional(),
      // Reference branch for the fresh worktree (no `origin/` prefix).
      // Omitted → the project's referenceBranch config default, else the
      // remote default branch.
      branch: z.string().min(1).optional(),
      // Initial prompt typed into the agent pane once it's up.
      prompt: z.string().min(1).max(10000).optional(),
      // Model override for the agent's launch command (`--model <model>`;
      // `provider/model` for opencode and pi — see buildAgentCmd). MODEL_RE
      // keeps it safe to embed in the single-quoted agent launch command.
      model: z.string().regex(MODEL_RE).max(100).optional(),
      // How much the agents may do before stopping to ask. Omitted → what
      // this project last had chosen, else the driver's default. Present is
      // taken as a person's choice and becomes the project's next default.
      // A posture the tool lacks is a 400, not a downgrade.
      permissionMode: z.enum(PERMISSION_MODES).optional(),
      // Sidebar group to file the worktree under, by id or name; a name
      // matching no group is created. Resolved before anything is
      // provisioned, so a typo'd group is not a half-built worktree.
      group: z.string().min(1).max(MAX_TITLE_LENGTH).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      const worktreeId = body.worktreeId ?? randomUUID()
      return streamProvisioned(c, worktreeId, async (onProgress) => {
        const groupId = body.group === undefined
          ? undefined
          : (await resolveGroup(body.project, body.group, { create: true })).groupId

        // Resolve the tool server-side: explicit --tool wins, else the
        // configured default (yaac tool set), else claude. This is the tool the
        // prewarm pool warms, so a bare create matches its spare.
        const tool = body.tool ?? (await getDefaultTool()) ?? 'claude'

        // Fast path: claim a prewarmed spare for this project + tool. A claim
        // returns the spare's own id and registers no provisioning row — the
        // unhidden worktree lists in the very next snapshot. A spare warmed
        // from a different branch is re-branched inside the claim.
        // Spares are warmed in tui mode, so an acp create can never claim one
        // — the spare's agent window already runs a TUI. Skipping the claim is
        // what keeps it from being retooled into a half-ACP session.
        //
        // Any posture but `bypass` skips it for the same shape of reason: a
        // spare's agent is ALREADY running, started in `bypass` (only a
        // sandboxed runtime warms spares, where that is the default).
        // Claiming one would hand back an unrestrained worktree to a user who
        // asked for `plan`, and silently — the claim never rewrites the row's
        // posture, so a restart would preserve it too. Cold-creating is the
        // honest answer; it costs the claim's saving, which is the price of
        // the posture actually being the one that was asked for.
        //
        // Resolved rather than read off the body, because an omitted posture
        // is not the same as `bypass`: this project may have last been used
        // in `plan`, and that is what the create below will pick up.
        const permissionMode = await resolvePermissionMode({
          projectSlug: body.project,
          tool,
          ...(body.permissionMode !== undefined ? { requested: body.permissionMode } : {}),
        })
        // A person picked this one; teach it to the project so the next
        // create — from any client — starts there. Only an explicit choice
        // writes, so a defaulted create never overwrites what was picked.
        //
        // Unless the choice was not really theirs. `bypass` is the only
        // posture pi can be launched in, so reaching it REQUIRES asking for
        // it — and recording that would turn "pi needs bypass" into "this
        // project runs unrestrained", quietly moving every later claude create
        // on the user's own machine. A pick with no alternative expresses
        // nothing about working style, so it teaches nothing.
        const forced = SUPPORTED_PERMISSION_MODES[tool].length === 1
        if (body.permissionMode !== undefined && !forced) {
          await recordProjectPermissionMode(body.project, body.permissionMode)
        }
        // A spare's agent is already running, and in `bypass` — so it can only
        // be handed to a create that resolved there. An ACP create is not
        // excluded for its mode but for its shape: a spare boots a `tui`
        // window, which is not a conversation this create could adopt.
        const claimed = body.mode === 'acp' || permissionMode !== 'bypass'
          ? undefined
          : await tryClaimPrewarmed(
            body.project, tool, onProgress, body.branch, body.model,
          )
        if (claimed) {
          // A claimed spare already has its row, so its group is filed here
          // rather than by the create below.
          if (groupId !== undefined) {
            await setWorktreeGroup(body.project, claimed.worktreeId, groupId)
          }
          // The spare's agent booted with no prompt; type it in now.
          if (body.prompt !== undefined) {
            onProgress('Sending initial prompt...')
            await typeInitialPrompt(claimed.jobName, claimed.tool, body.prompt)
          }
          return claimed
        }

        const opts: WorktreeCreateOptions = {
          worktreeId,
          onProgress,
          tool, // resolved default applies when --tool was omitted
        }
        if (body.branch) opts.branch = body.branch
        if (body.prompt !== undefined) opts.initialPrompt = body.prompt
        if (body.model !== undefined) opts.model = body.model
        if (body.mode !== undefined) opts.mode = body.mode
        if (body.installMissingTool === true) opts.installMissingTool = true
        opts.permissionMode = permissionMode
        if (groupId !== undefined) opts.groupId = groupId
        // Register before the long await so the row shows up instantly and
        // survives a browser reload (the stream keeps running server-side).
        registerProvisioning({
          worktreeId,
          projectSlug: body.project,
          tool,
          kind: 'create',
          ...(groupId !== undefined ? { groupId } : {}),
        })
        return await createWorktree(body.project, opts)
      })
    },
  )
  .post(
    '/restart',
    zv('json', z.object({
      worktreeId: z.string().min(1),
      // The webapp passes the worktree's project + tool (known from the
      // stopped entry) so its row renders during the resolve rather than
      // after it. Optional, and only that: `restartWorktree` registers the
      // entry itself once the resolve answers, so a caller that omits these
      // is tracked too — being in the registry is what exempts a restart
      // from the stale reaper, not a display detail.
      projectSlug: z.string().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      // No `mode` here, deliberately: a worktree comes back the way it went
      // down, so restart resolves it from `agent_sessions` rather than from
      // the caller. Accepting one would advertise a choice this route does
      // not have — it would be silently ignored. No `gitUser` either: the
      // identity a worktree commits under is a server setting now, so a
      // caller sending one would be a second answer to a settled question.
    })),
    async (c) => {
      const body = c.req.valid('json')
      // Head start for a caller that already knows the answer, so the row is
      // on screen while the resolve runs; `restartWorktree` registers for
      // everyone else. Not the reaper interlock — that is the register
      // inside restartWorktree, which no caller can skip.
      if (body.projectSlug) {
        // The group is read here rather than left to restartWorktree's own
        // register: that one `ensure`s, so it would not correct this entry,
        // and a groupless head start would park the restarting row at the top
        // of the sidebar for the whole restart. Read, not taken from the
        // caller — the row is what the sidebar files the worktree under.
        const row = await findWorktreeRow(body.worktreeId)
        registerProvisioning({
          worktreeId: body.worktreeId,
          projectSlug: body.projectSlug,
          tool: body.tool ?? 'claude',
          kind: 'restart',
          ...(row?.groupId !== undefined ? { groupId: row.groupId } : {}),
        })
      }
      return streamProvisioned(c, body.worktreeId, (onProgress) =>
        restartWorktree(body.worktreeId, { onProgress }))
    },
  )
  .post(
    '/stop',
    zv('json', z.object({ worktreeId: z.string().min(1) })),
    async (c) => {
      const { worktreeId } = c.req.valid('json')
      const info = await stopWorktree(worktreeId)
      return c.json(info)
    },
  )
  // Acknowledge that the user has viewed an abnormal death's detail, clearing
  // the "Stopped worktrees" notification dot / row highlight. Persisted on the
  // worktree row so the mark is durable and shared across clients.
  .post(
    '/mark-death-seen',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      worktreeId: z.string().min(1),
    })),
    async (c) => {
      const { projectSlug, worktreeId } = c.req.valid('json')
      await recordDeathSeen(projectSlug, worktreeId)
      return c.body(null, 204)
    },
  )
  // The same acknowledgement for a whole project at once ("mark all as read"),
  // so a burst of deaths doesn't have to be clicked through row by row.
  .post(
    '/mark-all-deaths-seen',
    zv('json', z.object({ projectSlug: z.string().min(1) })),
    async (c) => {
      await recordAllDeathsSeen(c.req.valid('json').projectSlug)
      return c.body(null, 204)
    },
  )
  // The sidebar-group routes. All take an explicit projectSlug (like
  // /mark-death-seen) rather than resolving a container: a group's members can
  // be stopped worktrees with no pod to resolve, and the group itself has no
  // container at all.
  /**
   * The in-worktree command channel, for a runtime whose workspaces reach
   * this server directly — `yaac-mama` inside a containerless worktree.
   *
   * The push half of what the k8s proxy's queue does by pull. A pod cannot
   * dial the host, so its requests are held at the proxy and collected by
   * the reconcile drain; a host process just posts here. Both land in
   * `runMamaCommand`, which is the single place the command allowlist lives.
   *
   * Authenticated per WORKTREE, not per user: the bearer is the opaque
   * token minted for this worktree at create, and it is what identifies the
   * caller — the request never says which worktree it is, so nothing it
   * sends can claim to be another one. Unauthenticated at the global gate
   * (`isPublicPath`) precisely because the credential it carries is not the
   * server secret.
   */
  .post(
    '/mama',
    zv('json', z.object({
      command: z.string().min(1).max(32),
      args: z.record(z.string(), z.string()).optional(),
      body: z.string().max(10000).optional(),
    })),
    async (c) => {
      // A k8s worktree has a channel, and it is not this one — it holds no
      // token to present, and issuing it one would put a server credential
      // inside the sandbox the whole substrate exists to keep it out of.
      if (worktreeDriver().kind !== 'containerless') {
        throw new ServerError(
          'NOT_SUPPORTED',
          'This server runs worktrees in containers, where yaac-mama speaks to the egress '
          + 'proxy rather than to the server.',
        )
      }
      const bearer = c.req.header('authorization')?.replace(/^Bearer\s+/i, '') ?? ''
      const caller = await findWorktreeByMamaToken(bearer)
      if (!caller) throw new ServerError('BAD_BEARER', 'unknown or revoked yaac-mama token')

      const { command, args, body } = c.req.valid('json')
      // The caller's tool comes off the runtime, the same fact the drain
      // reads from pod labels — not from the request, which could claim any.
      const handle = await worktreeDriver().find(caller.worktreeId).catch(() => null)
      const outcome = await runMamaCommand(
        {
          workspaceId: caller.worktreeId,
          projectSlug: caller.projectSlug,
          ...(handle?.declaredTool !== undefined ? { tool: handle.declaredTool } : {}),
        },
        { command, args: args ?? {}, body: body ?? '' },
      )
      // 422 for a refusal, mirroring what the proxy hands a queued caller,
      // so the script's two transports report failure identically.
      return outcome.ok
        ? c.json({ output: outcome.output })
        : c.json({ error: outcome.error }, 422)
    },
  )
  // Every group of a project, for a client that holds no snapshot — the CLI's
  // `yaac group list`. The webapp reads the same rows off `/events`.
  .get(
    '/group/list',
    zv('query', z.object({ project: z.string().optional() })),
    async (c) => {
      const { project } = c.req.valid('query')
      return c.json({ groups: await listWorktreeGroups(project || undefined) })
    },
  )
  .post(
    '/group/create',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      // The founding worktree, when the group is being made around one (the
      // sidebar's "new group from this worktree"). Omitted, the group is born
      // empty and pinned — `yaac group create` names a group before anything
      // is in it.
      worktreeId: z.string().min(1).optional(),
      name: z.string().min(1).max(MAX_TITLE_LENGTH),
    })),
    async (c) => {
      const { projectSlug, worktreeId, name } = c.req.valid('json')
      const group = await createWorktreeGroup(projectSlug, name, worktreeId ?? null)
      // The stored name, not the typed one: the store normalizes (whitespace
      // collapsed, length capped), and a caller that echoes what it sent
      // would report a group that is not the one now in the table.
      return c.json({ groupId: group.groupId, name: group.name })
    },
  )
  .post(
    '/group/rename',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      groupId: z.string().min(1),
      name: z.string().min(1).max(MAX_TITLE_LENGTH),
    })),
    async (c) => {
      const { projectSlug, groupId, name } = c.req.valid('json')
      await renameWorktreeGroup(projectSlug, groupId, name)
      return c.body(null, 204)
    },
  )
  .post(
    '/group/set-pinned',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      groupId: z.string().min(1),
      pinned: z.boolean(),
    })),
    async (c) => {
      const { projectSlug, groupId, pinned } = c.req.valid('json')
      await setWorktreeGroupPinned(projectSlug, groupId, pinned)
      return c.body(null, 204)
    },
  )
  .post(
    '/group/delete',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      groupId: z.string().min(1),
    })),
    async (c) => {
      const { projectSlug, groupId } = c.req.valid('json')
      await deleteWorktreeGroup(projectSlug, groupId)
      return c.body(null, 204)
    },
  )
  // File a worktree under a group NAMED rather than identified — `yaac group
  // move` and `yaac-mama group move`, where the caller is a person or an
  // agent who has seen names and never an id. Distinct from `/set-group`
  // below, which is the sidebar's precise instrument: a drag onto a group
  // that has since been deleted must fail, not resurrect it by name.
  .post(
    '/group/move',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      worktreeId: z.string().min(1),
      // A group id or name; null returns the worktree to the default list.
      group: z.string().min(1).max(MAX_TITLE_LENGTH).nullable(),
      // Create the group when the name matches none. For a caller that is
      // naming the group rather than picking one.
      create: z.boolean().optional(),
    })),
    async (c) => {
      const { projectSlug, worktreeId, group, create } = c.req.valid('json')
      // An id or its unique short prefix, which is what every surface prints
      // — the membership write itself matches exactly, so a prefix reaching
      // it would file nothing and report success.
      const found = await resolveSessionInProject(projectSlug, worktreeId)
      if (!found.ok) {
        // An ambiguous prefix is an under-specified request, not a missing
        // worktree: the caller holds the right id and typed too little of
        // it, so saying "no such worktree" sends it looking for the wrong
        // thing.
        throw found.reason === 'ambiguous'
          ? new ServerError(
            'VALIDATION',
            `Ambiguous worktree prefix in ${projectSlug}: ${worktreeId} — use a longer prefix`,
          )
          : new ServerError('NOT_FOUND', `No such worktree in ${projectSlug}: ${worktreeId}`)
      }
      const resolved = found.worktreeId
      const target = group === null
        ? null
        : await resolveGroup(projectSlug, group, { create: create ?? false })
      await setWorktreeGroup(projectSlug, resolved, target?.groupId ?? null)
      // The NAME too: the caller may have passed an id (the ambiguity error
      // tells it to), and echoing a uuid back at a person is not an answer.
      return c.json({ groupId: target?.groupId ?? null, name: target?.name ?? null })
    },
  )
  // File a worktree under a group, or return it to the default list (null).
  .post(
    '/set-group',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      worktreeId: z.string().min(1),
      groupId: z.string().min(1).nullable(),
    })),
    async (c) => {
      const { projectSlug, worktreeId, groupId } = c.req.valid('json')
      await setWorktreeGroup(projectSlug, worktreeId, groupId)
      return c.body(null, 204)
    },
  )
  .post('/provisioning/:id/dismiss', (c) => {
    // Drop a provisioning entry (only meaningful for a failed one — successful
    // ones self-clean once the real worktree lists). Idempotent for any id.
    removeProvisioning(c.req.param('id'))
    return c.body(null, 204)
  })
  .post(
    '/:id/title',
    zv('json', z.object({ title: z.string().max(500) })),
    async (c) => {
      // The RECORD, not a container: a title lives on the host, so renaming
      // a waiting, stopped or just-died worktree is fine — and renaming one
      // before restarting it is a normal thing to do. Resolving a container
      // here 404'd every worktree without a live pod.
      const { projectSlug, worktreeId } = await resolveWorktreeRecord(c.req.param('id'))
      await setWorktreeTitle(projectSlug, worktreeId, c.req.valid('json').title)
      return c.body(null, 204)
    },
  )
  // A worktree's conversations, active first — `yaac worktree agents <id>`
  // and the webapp's history list.
  .get('/:id/agent-sessions', async (c) => {
    // Resolved from the record, not a pod: a stopped worktree keeps its
    // conversations, and listing them is most of the point of the command.
    const { projectSlug, worktreeId } = await resolveWorktreeRecord(c.req.param('id'))
    const links = await listWorktreeAgentSessions(projectSlug, worktreeId)
    return c.json(links.map((l) => toAgentSessionEntry(l)))
  })
  // One conversation's history, as the events the chat pane renders. Resolved
  // from the record for the same reason the listing above is, and the whole
  // point of it: a stopped worktree's conversation is still readable, which is
  // what the stopped-worktrees view shows instead of just the founding ask.
  // A conversation whose tool leaves no host transcript refuses with 501.
  .get('/:id/agent-sessions/:sessionId/transcript', async (c) => {
    const { projectSlug, worktreeId } = await resolveWorktreeRecord(c.req.param('id'))
    const events = await getAgentSessionTranscript(
      projectSlug, worktreeId, c.req.param('sessionId'),
    )
    return c.json({ events })
  })
  .get('/:id/terminals', async (c) => {
    const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await listWorktreeTerminals(jobName))
  })
  // The worktree's review diff — everything changed in the worktree since it
  // forked from the base branch (committed + working + untracked). An optional
  // `base` overrides the branch it's diffed against (fork point vs origin/<base>).
  .get(
    '/:id/changes',
    zv('query', z.object({ base: z.string().min(1).max(255).optional() })),
    async (c) => c.json(await getWorktreeChanges(c.req.param('id'), c.req.valid('query').base)),
  )
  // Create a scratch-shell window in the session's `yaac` tmux session,
  // returning its entry so the client can open a pane immediately.
  .post('/:id/terminals', async (c) => {
    const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await createShellWindow(jobName))
  })
  .post(
    '/:id/terminals/close',
    zv('json', z.object({ target: z.string().min(1) })),
    async (c) => {
      const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
      const { target } = c.req.valid('json')
      try {
        await killWindowTerminal(jobName, target)
      } catch (err) {
        throw new ServerError('VALIDATION', err instanceof Error ? err.message : String(err))
      }
      return c.body(null, 204)
    },
  )
  .get('/:id', async (c) => c.json(await getWorktreeDetail(c.req.param('id'))))
  // The egress and port-relay routes below refuse on a runtime that
  // mediates neither. Guarded BEFORE the id resolve, because what this
  // server can do is not a property of the worktree being asked about — a
  // 404 for an id that happens not to exist would hide the real answer.
  // The driver's own verbs still answer empty, which is what keeps the
  // snapshot composing them unconditionally.
  .get('/:id/blocked-hosts', async (c) => {
    requireDriverFeature('egress')
    return c.json(await getWorktreeBlockedHosts(c.req.param('id')))
  })
  // Allow a previously-blocked host (webapp click-to-allow). The proxy prunes
  // the host from its recorded blocked set, so the snapshot we push clears the
  // badge. Persist/fan-out policy lives in the domain verb.
  .post(
    '/:id/allow-host',
    zv('json', z.object({
      // A bare hostname or wildcard pattern — the grammar hostMatchesPattern
      // (#lib/allowed-hosts) matches against; no scheme/path/port.
      host: z.string().regex(/^[A-Za-z0-9*._-]+$/, 'host must be a bare hostname or *.wildcard pattern'),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      requireDriverFeature('egress')
      const { host, persist } = c.req.valid('json')
      await allowWorktreeHost(c.req.param('id'), host, { persist: persist ?? false })
      return c.body(null, 204)
    },
  )
  // Forward a detected-but-unforwarded port (webapp click-to-forward). The
  // port must be in the worktree's surfaced unforwarded set — the runtime
  // rejects anything else, so the route can't be driven to open an arbitrary
  // port. Persist/fan-out policy lives in the domain verb.
  .post(
    '/:id/forward-port',
    zv('json', z.object({
      containerPort: z.number().int().min(1).max(65535),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      requireDriverFeature('portRelay')
      const { containerPort, persist } = c.req.valid('json')
      const mapping = await forwardWorktreePort(
        c.req.param('id'), containerPort, { persist: persist ?? false },
      )
      return c.json(mapping)
    },
  )
  // Hide a detected port for this worktree (in-memory; resets with the server).
  // Same guard as forward-port: only a currently-surfaced port is
  // dismissable, so the dismissed set can't be grown arbitrarily.
  .post(
    '/:id/dismiss-port',
    zv('json', z.object({ containerPort: z.number().int().min(1).max(65535) })),
    async (c) => {
      requireDriverFeature('portRelay')
      await dismissWorktreePort(c.req.param('id'), c.req.valid('json').containerPort)
      return c.body(null, 204)
    },
  )
  .get('/:id/prompt', async (c) => {
    const prompt = await getWorktreePrompt(c.req.param('id'))
    return c.json({ prompt: prompt ?? '' })
  })
