import { randomUUID } from 'node:crypto'
import { Hono } from 'hono'
import { zv } from '#routes/validator'
import { z } from 'zod'
import {
  getWorktreeBlockedHosts,
  getWorktreeDetail,
  getWorktreePrompt,
  listActiveWorktrees,
  listStoppedWorktrees,
  registerProvisioning,
  removeProvisioning,
  resolveWorktreeContainer,
  resolveWorktreeRecord,
  restartWorktree,
  worktreeForkBranch,
  type WorktreeCreateOptions,
} from '#domain/worktrees'
import { createWorktree, stopWorktree, tryClaimPrewarmed } from '#domain/worktrees'
import { getWorktreeChanges } from '#runtime/k8s/worktrees'
import { typeInitialPrompt } from '#runtime/agents'
import { createShellWindow, killWindowTerminal, listWorktreeTerminals } from '#runtime/terminals'
import { allowWorktreeHost } from '#runtime/k8s/egress'
import { dismissWorktreePort, forwardWorktreePort } from '#runtime/k8s/forwarders'
import {
  listWorktreeAgentSessions,
  recordAllDeathsSeen,
  recordDeathSeen,
  setWorktreeBackground,
  setWorktreeTitle,
  toAgentSessionEntry,
} from '#records'
import { notifyWorktreeListChanged } from '#notify'
import { getDefaultTool } from '#records'
import { streamProvisioned } from '#routes/provisioned-stream'
import { ServerError } from '@yaac/shared/errors'
import { MODEL_RE } from '@yaac/shared/types'

export const worktreeApp = new Hono()
  .get(
    '/list',
    zv('query', z.object({ project: z.string().optional() })),
    async (c) => {
      const { project } = c.req.valid('query')
      return c.json(await listActiveWorktrees(project || undefined))
    },
  )
  .get(
    '/list-stopped',
    zv('query', z.object({
      project: z.string().optional(),
      limit: z.coerce.number().int().positive().optional(),
    })),
    async (c) => {
      const { project, limit } = c.req.valid('query')
      return c.json(await listStoppedWorktrees(project || undefined, limit))
    },
  )
  .post(
    '/create',
    zv('json', z.object({
      project: z.string().min(1),
      // Pre-generated by the webapp so the provisioning row is selectable and
      // reload-matchable before any round-trip; the CLI omits it and the
      // server mints one.
      worktreeId: z.string().uuid().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      // Which protocol drives the agent. `acp` needs a tool with an adapter
      // in the image; createWorktree rejects the combination before it
      // provisions anything.
      mode: z.enum(['tui', 'acp']).optional(),
      // Reference branch for the fresh worktree (no `origin/` prefix).
      // Omitted → the project's referenceBranch config default, else the
      // remote default branch.
      branch: z.string().min(1).optional(),
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
      // Initial prompt typed into the agent pane once it's up.
      prompt: z.string().min(1).max(10000).optional(),
      // Model override for the agent's launch command (`--model <model>`;
      // `provider/model` for opencode and pi — see buildAgentCmd). MODEL_RE
      // keeps it safe to embed in the single-quoted agent launch command.
      model: z.string().regex(MODEL_RE).max(100).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      const worktreeId = body.worktreeId ?? randomUUID()
      return streamProvisioned(c, worktreeId, async (onProgress) => {
        // Resolve the tool server-side: explicit --tool wins, else the
        // configured default (yaac tool set), else claude. This is the tool the
        // prewarm pool warms, so a bare create matches its spare.
        const tool = body.tool ?? (await getDefaultTool()) ?? 'claude'

        // Fast path: claim a prewarmed spare for this project + tool. A claim
        // returns the spare's own id and registers no provisioning row — the
        // unhidden worktree lists in the very next snapshot. A spare warmed
        // from a different branch is re-branched inside the claim.
        // Spares are warmed in tui mode, so an acp create can never claim one
        // — the spare's agent window already runs a TUI. Skipping the claim is
        // what keeps it from being retooled into a half-ACP session.
        const claimed = body.mode === 'acp'
          ? undefined
          : await tryClaimPrewarmed(
            body.project, tool, body.gitUser, onProgress, body.branch, body.model,
          )
        if (claimed) {
          // The spare's agent booted with no prompt; type it in now.
          if (body.prompt !== undefined) {
            onProgress('Sending initial prompt...')
            await typeInitialPrompt(claimed.jobName, claimed.tool, body.prompt)
          }
          return claimed
        }

        const opts: WorktreeCreateOptions = {
          worktreeId,
          onProgress,
          tool, // resolved default applies when --tool was omitted
        }
        if (body.branch) opts.branch = body.branch
        if (body.gitUser) opts.gitUser = body.gitUser
        if (body.prompt !== undefined) opts.initialPrompt = body.prompt
        if (body.model !== undefined) opts.model = body.model
        if (body.mode !== undefined) opts.mode = body.mode
        // Register before the long await so the row shows up instantly and
        // survives a browser reload (the stream keeps running server-side).
        registerProvisioning({ worktreeId, projectSlug: body.project, tool, kind: 'create' })
        return await createWorktree(body.project, opts)
      })
    },
  )
  .post(
    '/restart',
    zv('json', z.object({
      worktreeId: z.string().min(1),
      // The webapp passes the worktree's project + tool (known from the
      // stopped entry) so the provisioning row can render while restart
      // resolves the target authoritatively. The CLI omits them — it doesn't
      // need the row.
      projectSlug: z.string().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      // No `mode` here, deliberately: a worktree comes back the way it went
      // down, so restart resolves it from `agent_sessions` rather than from
      // the caller. Accepting one would advertise a choice this route does
      // not have — it would be silently ignored.
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      if (body.projectSlug) {
        registerProvisioning({
          worktreeId: body.worktreeId,
          projectSlug: body.projectSlug,
          tool: body.tool ?? 'claude',
          kind: 'restart',
        })
      }
      return streamProvisioned(c, body.worktreeId, (onProgress) =>
        restartWorktree(body.worktreeId, { gitUser: body.gitUser, onProgress }))
    },
  )
  .post(
    '/stop',
    zv('json', z.object({ worktreeId: z.string().min(1) })),
    async (c) => {
      const { worktreeId } = c.req.valid('json')
      const info = await stopWorktree(worktreeId)
      return c.json(info)
    },
  )
  // Acknowledge that the user has viewed an abnormal death's detail, clearing
  // the "Stopped worktrees" notification dot / row highlight. Persisted on the
  // worktree row so the mark is durable and shared across clients.
  .post(
    '/mark-death-seen',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      worktreeId: z.string().min(1),
    })),
    async (c) => {
      const { projectSlug, worktreeId } = c.req.valid('json')
      await recordDeathSeen(projectSlug, worktreeId)
      return c.body(null, 204)
    },
  )
  // The same acknowledgement for a whole project at once ("mark all as read"),
  // so a burst of deaths doesn't have to be clicked through row by row.
  .post(
    '/mark-all-deaths-seen',
    zv('json', z.object({ projectSlug: z.string().min(1) })),
    async (c) => {
      await recordAllDeathsSeen(c.req.valid('json').projectSlug)
      return c.body(null, 204)
    },
  )
  // Pin (or unpin) a worktree to the sidebar's "Background" section. Takes an
  // explicit projectSlug (like /mark-death-seen) rather than resolving the
  // container: the target may be a stopped worktree with no pod to resolve.
  .post(
    '/set-background',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      worktreeId: z.string().min(1),
      background: z.boolean(),
    })),
    async (c) => {
      const { projectSlug, worktreeId, background } = c.req.valid('json')
      await setWorktreeBackground(projectSlug, worktreeId, background)
      // Push a fresh snapshot so the sidebar regroups immediately.
      notifyWorktreeListChanged()
      return c.body(null, 204)
    },
  )
  .post('/provisioning/:id/dismiss', (c) => {
    // Drop a provisioning entry (only meaningful for a failed one — successful
    // ones self-clean once the real worktree lists). Idempotent for any id.
    removeProvisioning(c.req.param('id'))
    return c.body(null, 204)
  })
  .post(
    '/:id/title',
    zv('json', z.object({ title: z.string().max(500) })),
    async (c) => {
      // Resolve in any state — renaming a waiting or just-stopped worktree is
      // fine; the title lives on the host, not in the container.
      const { projectSlug, worktreeId } = await resolveWorktreeContainer(c.req.param('id'))
      await setWorktreeTitle(projectSlug, worktreeId, c.req.valid('json').title)
      // Push a fresh snapshot so the sidebar reflects the rename immediately.
      notifyWorktreeListChanged()
      return c.body(null, 204)
    },
  )
  // A worktree's conversations, active first — `yaac worktree agents <id>`
  // and the webapp's history list.
  .get('/:id/agent-sessions', async (c) => {
    // Resolved from the record, not a pod: a stopped worktree keeps its
    // conversations, and listing them is most of the point of the command.
    const { projectSlug, worktreeId } = await resolveWorktreeRecord(c.req.param('id'))
    const links = await listWorktreeAgentSessions(projectSlug, worktreeId)
    return c.json(links.map((l) => toAgentSessionEntry(l)))
  })
  .get('/:id/terminals', async (c) => {
    const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await listWorktreeTerminals(jobName))
  })
  // The worktree's review diff — everything changed in the worktree since it
  // forked from the base branch (committed + working + untracked). An optional
  // `base` overrides the branch it's diffed against (fork point vs origin/<base>).
  .get(
    '/:id/changes',
    zv('query', z.object({ base: z.string().min(1).max(255).optional() })),
    async (c) => {
      const { jobName, worktreeId, projectSlug } = await resolveWorktreeContainer(
        c.req.param('id'), { requireRunning: true },
      )
      // The branch the worktree forked from (its recorded base, e.g. main) —
      // the same source as the sidebar base label. Passed as the DEFAULT diff
      // base so committed work stays visible even after the agent renames and
      // pushes its branch, which makes the current branch's own @{upstream}
      // collapse the merge-base to HEAD. Cached, because this endpoint is
      // polled.
      const forkBranch = await worktreeForkBranch(projectSlug, worktreeId)
      return c.json(await getWorktreeChanges(
        jobName, c.req.valid('query').base, forkBranch ?? undefined,
      ))
    },
  )
  // Create a scratch-shell window in the session's `yaac` tmux session,
  // returning its entry so the client can open a pane immediately.
  .post('/:id/terminals', async (c) => {
    const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await createShellWindow(jobName))
  })
  .post(
    '/:id/terminals/close',
    zv('json', z.object({ target: z.string().min(1) })),
    async (c) => {
      const { jobName } = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
      const { target } = c.req.valid('json')
      try {
        await killWindowTerminal(jobName, target)
      } catch (err) {
        throw new ServerError('VALIDATION', err instanceof Error ? err.message : String(err))
      }
      return c.body(null, 204)
    },
  )
  .get('/:id', async (c) => c.json(await getWorktreeDetail(c.req.param('id'))))
  .get('/:id/blocked-hosts', async (c) => c.json(await getWorktreeBlockedHosts(c.req.param('id'))))
  // Allow a previously-blocked host (webapp click-to-allow). The proxy prunes
  // the host from its recorded blocked set, so the snapshot we push clears the
  // badge. Persist/fan-out policy lives in allowWorktreeHost.
  .post(
    '/:id/allow-host',
    zv('json', z.object({
      // A bare hostname or wildcard pattern — the grammar hostMatchesPattern
      // (default-allowed-hosts.ts) matches against; no scheme/path/port.
      host: z.string().regex(/^[A-Za-z0-9*._-]+$/, 'host must be a bare hostname or *.wildcard pattern'),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      const { host, persist } = c.req.valid('json')
      const target = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
      await allowWorktreeHost(
        { worktreeId: target.worktreeId, projectSlug: target.projectSlug },
        host,
        { persist: persist ?? false },
      )
      notifyWorktreeListChanged()
      return c.body(null, 204)
    },
  )
  // Forward a detected-but-unforwarded port (webapp click-to-forward). The
  // port must be in the worktree's surfaced unforwarded set — forwardWorktreePort
  // rejects anything else, so the route can't be driven to open an arbitrary
  // port. Persist/fan-out policy lives in forwardWorktreePort.
  .post(
    '/:id/forward-port',
    zv('json', z.object({
      containerPort: z.number().int().min(1).max(65535),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      const { containerPort, persist } = c.req.valid('json')
      const target = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
      const mapping = await forwardWorktreePort(
        { worktreeId: target.worktreeId, projectSlug: target.projectSlug, jobName: target.jobName },
        containerPort,
        { persist: persist ?? false },
      )
      // Fresh snapshot moves the port from unforwardedPorts into
      // forwardedPorts, self-clearing the popover row.
      notifyWorktreeListChanged()
      return c.json(mapping)
    },
  )
  // Hide a detected port for this worktree (in-memory; resets with the server).
  // Same guard as forward-port: only a currently-surfaced port is
  // dismissable, so the dismissed set can't be grown arbitrarily.
  .post(
    '/:id/dismiss-port',
    zv('json', z.object({ containerPort: z.number().int().min(1).max(65535) })),
    async (c) => {
      const { containerPort } = c.req.valid('json')
      const target = await resolveWorktreeContainer(c.req.param('id'), { requireRunning: true })
      if (!dismissWorktreePort(target.worktreeId, containerPort)) {
        throw new ServerError(
          'CONFLICT',
          `port ${containerPort} is not an unforwarded listener in session ${target.worktreeId.slice(0, 8)}`,
        )
      }
      notifyWorktreeListChanged()
      return c.body(null, 204)
    },
  )
  .get('/:id/prompt', async (c) => {
    const prompt = await getWorktreePrompt(c.req.param('id'))
    return c.json({ prompt: prompt ?? '' })
  })
