import { randomBytes } from 'node:crypto'
import { workspaceDriver } from '#drivers/driver'
import { tmuxCmd } from '#runtime/agents'
import { createOutputBatcher } from '@yaac/shared/batcher'
import type { WorkspacePaths } from '#drivers/contract'

const DEFAULT_COLS = 80
const DEFAULT_ROWS = 24

/**
 * What a terminal attaches to inside the workspace:
 *  - 'agent'          the agent window of the `yaac` tmux session.
 *  - 'window:@<id>'   any other window (an initCommands dev server, a
 *    scratch shell, …), via a per-client grouped session so other viewers'
 *    active window is never changed.
 *  - 'native'         the CLI's full attach: a per-client grouped session
 *    with tmux chrome intact (status bar, prefix keys, `C-b d`). Grouped so
 *    each client keeps its own size and current window, and
 *    `destroy-unattached` cleans up on disconnect.
 *  - 'shell'          a raw `$SHELL` with no tmux (the CLI's
 *    `workspace shell`); exiting the shell ends the connection.
 */
type PtyTarget = string

const WINDOW_ID = /^@[0-9]{1,6}$/

/** Coerce a client-supplied target (a WS query param) to a PtyTarget;
 *  anything unrecognized means the agent. */
function parsePtyTarget(raw: string | undefined): PtyTarget {
  if (raw === undefined) return 'agent'
  if (raw === 'agent' || raw === 'native' || raw === 'shell') return raw
  if (raw.startsWith('window:') && WINDOW_ID.test(raw.slice('window:'.length))) return raw
  return 'agent'
}

/** Name for a per-client tmux view session. Generated by the server so it
 *  can later address the session (`kill-session -t <view>` on close). */
function newViewName(): string {
  return `view-${randomBytes(4).toString('hex')}`
}

/**
 * In-workspace argv for a tab's PTY, spawned under a real PTY by the driver
 * (the same transport the CLI's `workspace attach` uses via /pty/attach).
 *
 * Each target attaches through a per-client grouped view session pinned to
 * one window, so a webapp tab is a tmux window:
 *  - `destroy-unattached on`: the view dies on detach; the windows live on.
 *  - `status off`: no tmux status bar; the webapp tab strip is the window
 *    list.
 *  - `prefix None`: no tmux key bindings, so C-b reaches the agent. Mouse
 *    bindings (root key table) still work.
 *
 * The view is created detached, already sized and `status off`, then
 * attached. `destroy-unattached` is set after the attach so nothing reaps
 * the view in between.
 *
 * Window sizing uses tmux's `window-size latest`: a shared window takes the
 * size of the client that most recently attached, resized or typed. tmux
 * (3.1+) applies it during the resize itself, before redrawing; a separate
 * `resize-window` would lag and show overflow dots. The window is selected
 * before the attach so the attach makes this client the latest. A ghost
 * client from a dropped exec never resizes or types, so it only regains a
 * window briefly, and the attach-time ghost sweep reaps it. `window-size`
 * is set explicitly so a user's tmux config cannot freeze the size.
 */
function attachArgs(
  target: PtyTarget,
  viewName: string,
  size: { cols?: number; rows?: number },
  paths: WorkspacePaths,
): string[] {
  const tmux = tmuxCmd(paths)
  const cols = size.cols ?? DEFAULT_COLS
  const rows = size.rows ?? DEFAULT_ROWS
  // The has-session guard matters: before setup has created the `yaac`
  // session, `new-session -t yaac` silently creates a new group named
  // `yaac` holding a bare shell, and every later view would resolve to it.
  // Failing lets the client's reconnect loop retry until setup finishes.
  const create = `${tmux} has-session -t =yaac 2>/dev/null`
    + ` && ${tmux} new-session -d -t yaac -s ${viewName} -x ${cols} -y ${rows}`

  // Native (CLI) attach keeps the tmux chrome and the group's current
  // window; only destroy-unattached differs from `attach-session -t yaac`.
  // It switches windows live, so it sets no window's size policy.
  if (target === 'native') {
    return [
      'sh', '-c',
      create
      + ` && exec ${tmux} attach-session -t ${viewName}`
      + ' \\; set-option destroy-unattached on',
    ]
  }

  // The agent is the lowest-index window (`^`): it is created first and
  // others are appended, as in the terminals listing.
  const window = `${viewName}:${target.startsWith('window:') ? target.slice('window:'.length) : '^'}`
  return [
    'sh', '-c',
    create
    + ` \\; set-option -t ${viewName} status off`
    + ` \\; set-option -t ${viewName} prefix None`
    + ` \\; select-window -t '${window}'`
    + ` \\; set-option -w -t '${window}' window-size latest`
    + ` && exec ${tmux} attach-session -t ${viewName}`
    + ' \\; set-option destroy-unattached on',
  ]
}

/** Command listing every tmux session name in the workspace. */
function listTmuxSessionsCmd(paths: WorkspacePaths): string {
  return `${tmuxCmd(paths)} list-sessions -F '#{session_name}'`
}

/** Ghost views among `names`: view sessions no live connection owns. The
 *  name-shape check keeps other sessions (yaac, user-created) off the kill
 *  list even if they start with "view-". */
function ghostViews(names: string[], live: ReadonlySet<string>): string[] {
  return names.filter((n) => /^view-[0-9a-f]{8}$/.test(n) && !live.has(n))
}

/** One tmux invocation killing all the given view sessions; the command
 *  sequence keeps going past a view that already died on its own. */
function killViewsCmd(views: string[], paths: WorkspacePaths): string {
  return `${tmuxCmd(paths)} ${views.map((v) => `kill-session -t ${v}`).join(' \\; ')}`
}

/**
 * Reap ghost view sessions in a workspace. A view normally dies with its
 * connection (kill-session on close, destroy-unattached as backstop), but
 * an ungraceful end (server crash, a dropped exec after a laptop sleep)
 * leaves a tmux client pinning its view "attached" forever; dozens have
 * been seen. Swept on every fresh attach. `live` is read after the listing,
 * so views attached mid-sweep are never treated as ghosts.
 */
async function sweepGhostViews(
  jobName: string,
  live: ReadonlySet<string>,
  paths: WorkspacePaths,
): Promise<void> {
  let listed: { stdout: string }
  try {
    listed = await workspaceDriver().exec(jobName, listTmuxSessionsCmd(paths), { maxAttempts: 1 })
  } catch {
    return // pod gone or tmux not up yet — nothing to sweep
  }
  const names = listed.stdout.split('\n').map((s) => s.trim()).filter(Boolean)
  const ghosts = ghostViews(names, live)
  if (ghosts.length === 0) return
  try {
    await workspaceDriver().exec(jobName, killViewsCmd(ghosts, paths), { maxAttempts: 1 })
  } catch {
    // Raced away (view self-destroyed, workspace stopping); fine.
  }
}

/**
 * Detach a client by killing its view session. With `prefix None` there is
 * no detach keystroke, and dropping the PTY stream does not always stop the
 * in-workspace tmux client first. Best-effort: a missing session or a gone
 * workspace is fine.
 */
async function killViewSession(
  jobName: string,
  viewName: string,
  paths: WorkspacePaths,
): Promise<void> {
  try {
    await workspaceDriver().exec(
      jobName,
      `${tmuxCmd(paths)} kill-session -t ${viewName}`,
      { maxAttempts: 1 },
    )
  } catch {
      // Nothing to clean up.
  }
}

interface ControlMessage {
  type: 'resize' | 'signal' | 'ping'
  cols?: number
  rows?: number
  name?: string
  /** Ping only: an opaque client stamp echoed in the pong so the client can
   *  time the round trip. */
  t?: number
}

/** Parse a text control frame. Returns null for anything unrecognized. */
function parseControl(text: string): ControlMessage | null {
  let obj: unknown
  try {
    obj = JSON.parse(text)
  } catch {
    return null
  }
  if (!obj || typeof obj !== 'object') return null
  const t = (obj as { type?: unknown }).type
  if (t !== 'resize' && t !== 'signal' && t !== 'ping') return null
  return obj as ControlMessage
}

/** The PTY surface the bridge needs (in production, the driver's `pty`
 *  stream). */
interface PtyLike {
  onData(cb: (data: string) => void): void
  onExit(cb: (e: { exitCode: number }) => void): void
  write(data: string): void
  resize(cols: number, rows: number): void
  kill(signal?: string): void
}

/** The socket surface (in production, the `ws` WebSocket via WSContext.raw). */
export interface SocketLike {
  send(data: string | Uint8Array): void
  close(code?: number, reason?: string): void
  onMessage(cb: (data: string | Buffer | ArrayBuffer, isBinary: boolean) => void): void
  onClose(cb: () => void): void
}

function toText(data: string | Buffer | ArrayBuffer): string {
  if (typeof data === 'string') return data
  return Buffer.from(data as ArrayBuffer).toString('utf8')
}

/** How long after the graceful tmux detach to force-kill the PTY. */
export const DETACH_GRACE_MS = 400

/**
 * Wire a PTY to a socket:
 *   - PTY output  → binary frames to the client
 *   - binary in   → PTY stdin (keystrokes)
 *   - text in     → control: {resize}/{signal}/{ping}
 *   - PTY exit    → close the socket
 *   - socket close→ detach tmux gracefully, then kill the PTY
 *
 * Detaching first matters: killing the PTY stream does not reliably end the
 * tmux client inside the workspace, and a leaked client keeps its view
 * session alive forever. `detach` (the in-workspace kill-session) runs
 * again at the grace deadline to catch a close that raced the attach, just
 * before the PTY is force-killed.
 */
function bridge(
  ptyProc: PtyLike,
  sock: SocketLike,
  detach?: () => void,
): void {
  // Batch output into one WebSocket message per burst (see
  // @yaac/shared/batcher). streamd batches at the source for k8s, but the
  // containerless driver's host PTY delivers event by event. Leading-edge
  // flushing means a lone keystroke echo is not delayed.
  const out = createOutputBatcher((chunk) => {
    try {
      sock.send(Buffer.from(chunk, 'utf8'))
    } catch {
      // Socket gone; the close handler kills the PTY.
    }
  })

  ptyProc.onData((d) => out.push(d))

  ptyProc.onExit(({ exitCode }) => {
    out.flush() // ordering: all output precedes the close
    try {
      sock.close(1000, `pty exited (${exitCode})`)
    } catch {
      // already closed
    }
  })

  sock.onMessage((data, isBinary) => {
    if (isBinary) {
      ptyProc.write(toText(data))
      return
    }
    const ctrl = parseControl(toText(data))
    if (!ctrl) return
    if (ctrl.type === 'resize' && ctrl.cols && ctrl.rows) {
      ptyProc.resize(ctrl.cols, ctrl.rows)
    } else if (ctrl.type === 'signal' && ctrl.name) {
      ptyProc.kill(ctrl.name)
    } else if (ctrl.type === 'ping') {
      // Echo the client's stamp so it can time the round trip (the
      // frontend's link-quality store). A bare ping (the CLI's keepalive)
      // gets a bare pong.
      sock.send(typeof ctrl.t === 'number' && Number.isFinite(ctrl.t)
        ? JSON.stringify({ type: 'pong', t: ctrl.t })
        : '{"type":"pong"}')
    }
  })

  sock.onClose(() => {
    out.dispose()
    detach?.()
    setTimeout(() => {
      detach?.()
      try {
        ptyProc.kill()
      } catch {
        // already gone
      }
    }, DETACH_GRACE_MS)
  })
}

/**
 * Coerce client-supplied dimensions (WS query params) into a size.
 * Invalid or absurd values become `undefined` (80x24 default). Spawning at
 * the browser's real size avoids the cold-start reflow that garbles
 * full-screen TUIs.
 */
function parsePtySize(
  colsRaw: string | undefined,
  rowsRaw: string | undefined,
): { cols?: number; rows?: number } {
  const clamp = (v: string | undefined): number | undefined => {
    const n = Math.trunc(Number(v))
    return Number.isFinite(n) && n >= 1 && n <= 1000 ? n : undefined
  }
  return { cols: clamp(colsRaw), rows: clamp(rowsRaw) }
}

/**
 * Live tmux view sessions per unit, for the ghost sweep: any `view-*`
 * session not listed here belongs to a dead connection and is reaped.
 * Server-wide so a sweep can tell another live tab's view from a ghost.
 */
const liveViews = new Map<string, Set<string>>()

/**
 * Attach one webapp/CLI terminal connection to a workspace: open the PTY
 * stream for the requested target and wire it to `socket`. `query` is the
 * raw /pty/attach query (target and grid size), validated here. Everything
 * the connection creates in the workspace (its view session) is reclaimed
 * here on close.
 */
export function attachPty(
  jobName: string,
  socket: SocketLike,
  query: { target?: string; cols?: string; rows?: string },
): void {
  const target = parsePtyTarget(query.target)
  const size = parsePtySize(query.cols, query.rows)
  const paths = workspaceDriver().workspacePaths(jobName)

  // 'shell' has no tmux, so no view session to register, sweep, resize or
  // kill. `$SHELL` because zsh is only guaranteed in the image, not on a
  // containerless host.
  if (target === 'shell') {
    bridge(workspaceDriver().dialPty(jobName, ['sh', '-c', 'exec "${SHELL:-sh}" -l'], size), socket)
    return
  }

  const viewName = newViewName()
  // Register this view before the sweep's listing so a concurrent attach
  // can never reap it (see sweepGhostViews).
  const views = liveViews.get(jobName) ?? new Set<string>()
  views.add(viewName)
  liveViews.set(jobName, views)
  void sweepGhostViews(jobName, views, paths)

  const ptyProc = workspaceDriver()
    .dialPty(jobName, attachArgs(target, viewName, size, paths), size)
  bridge(ptyProc, socket, () => {
    views.delete(viewName)
    // Only remove the entry if it is still ours: detach runs twice (again at
    // the grace deadline), and by then a new connection may have installed
    // a fresh set. Deleting that would hide the new view from the next
    // sweep, and reconnecting attaches would keep killing each other's
    // views.
    if (views.size === 0 && liveViews.get(jobName) === views) liveViews.delete(jobName)
    void killViewSession(jobName, viewName, paths)
  })
}
