import { randomUUID } from 'node:crypto'
import { Hono } from 'hono'
import { zv } from '#routes/validator'
import { z } from 'zod'
import { listActiveSessions } from '#features/sessions/list'
import { listDeletedSessions } from '#features/sessions/deleted-list'
import { recordDeathSeen, setSessionBackground, setSessionTitle } from '#features/sessions/store'
import { getSessionDetail, getSessionBlockedHosts, getSessionPrompt } from '#features/sessions/detail'
import { deleteSession } from '#features/sessions/delete'
import { restartSession } from '#features/sessions/restart'
import { createSession, type SessionCreateOptions } from '#features/sessions/create'
import { typeInitialPrompt, MODEL_RE } from '#features/sessions/agent-command'
import { tryClaimPrewarmed } from '#features/images'
import { getDefaultTool } from '#features/projects'
import { registerProvisioning, removeProvisioning } from '#features/sessions/provisioning'
import { streamProvisioned } from '#routes/provisioned-stream'
import { ServerError } from '@yaac/shared/errors'
import { allowSessionHost } from '#features/sessions/egress/allow-host'
import { forwardSessionPort } from '#features/sessions/forwarders/forward-port'
import { dismissSessionPort } from '#features/sessions/forwarders/port-detector'
import { resolveSessionContainer } from '#features/sessions/resolve'
import { notifySessionListChanged } from '#features/sessions/notify'
import { createShellWindow, listSessionTerminals, killWindowTerminal } from '#features/terminals'
import { getSessionChanges } from '#features/sessions/changes'
import { worktreeUpstreamBranch } from '#platform/git'
import { repoDir } from '@yaac/shared/project-paths'

export const sessionApp = new Hono()
  .get(
    '/list',
    zv('query', z.object({ project: z.string().optional() })),
    async (c) => {
      const { project } = c.req.valid('query')
      return c.json(await listActiveSessions(project || undefined))
    },
  )
  .get(
    '/list-deleted',
    zv('query', z.object({
      project: z.string().optional(),
      limit: z.coerce.number().int().positive().optional(),
    })),
    async (c) => {
      const { project, limit } = c.req.valid('query')
      return c.json(await listDeletedSessions(project || undefined, limit))
    },
  )
  .post(
    '/create',
    zv('json', z.object({
      project: z.string().min(1),
      // Pre-generated by the webapp so the provisioning row is selectable and
      // reload-matchable before any round-trip; the CLI omits it and the
      // server mints one.
      sessionId: z.string().uuid().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      // Reference branch for the fresh worktree (no `origin/` prefix).
      // Omitted → the project's referenceBranch config default, else the
      // remote default branch.
      branch: z.string().min(1).optional(),
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
      // Initial prompt typed into the agent pane once it's up.
      prompt: z.string().min(1).max(10000).optional(),
      // Model override for the agent's launch command (`--model <model>`;
      // `provider/model` for opencode and pi — see buildAgentCmd). MODEL_RE
      // keeps it safe to embed in the single-quoted agent launch command.
      model: z.string().regex(MODEL_RE).max(100).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      const sessionId = body.sessionId ?? randomUUID()
      return streamProvisioned(c, sessionId, async (onProgress) => {
        // Resolve the tool server-side: explicit --tool wins, else the
        // configured default (yaac tool set), else claude. This is the tool the
        // prewarm pool warms, so a bare create matches its spare.
        const tool = body.tool ?? (await getDefaultTool()) ?? 'claude'

        // Fast path: claim a prewarmed spare for this project + tool. A claim
        // returns the spare's own id and registers no provisioning row — the
        // unhidden session lists in the very next snapshot. A spare warmed
        // from a different branch is re-branched inside the claim.
        const claimed = await tryClaimPrewarmed(
          body.project, tool, body.gitUser, onProgress, body.branch, body.model,
        )
        if (claimed) {
          // The spare's agent booted with no prompt; type it in now.
          if (body.prompt !== undefined) {
            onProgress('Sending initial prompt...')
            await typeInitialPrompt(claimed.jobName, claimed.tool, body.prompt)
          }
          return claimed
        }

        const opts: SessionCreateOptions = {
          sessionId,
          onProgress,
          tool, // resolved default applies when --tool was omitted
        }
        if (body.branch) opts.branch = body.branch
        if (body.gitUser) opts.gitUser = body.gitUser
        if (body.prompt !== undefined) opts.initialPrompt = body.prompt
        if (body.model !== undefined) opts.model = body.model
        // Register before the long await so the row shows up instantly and
        // survives a browser reload (the stream keeps running server-side).
        registerProvisioning({ sessionId, projectSlug: body.project, tool, kind: 'create' })
        return await createSession(body.project, opts)
      })
    },
  )
  .post(
    '/restart',
    zv('json', z.object({
      sessionId: z.string().min(1),
      // The webapp passes the session's project + tool (known from the deleted
      // entry) so the provisioning row can render while restart resolves the
      // target authoritatively. The CLI omits them — it doesn't need the row.
      projectSlug: z.string().optional(),
      tool: z.enum(['claude', 'codex', 'opencode', 'pi']).optional(),
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      if (body.projectSlug) {
        registerProvisioning({
          sessionId: body.sessionId,
          projectSlug: body.projectSlug,
          tool: body.tool ?? 'claude',
          kind: 'restart',
        })
      }
      return streamProvisioned(c, body.sessionId, (onProgress) =>
        restartSession(body.sessionId, {
          gitUser: body.gitUser,
          onProgress,
        }))
    },
  )
  .post(
    '/delete',
    zv('json', z.object({ sessionId: z.string().min(1) })),
    async (c) => {
      const { sessionId } = c.req.valid('json')
      const info = await deleteSession(sessionId)
      return c.json(info)
    },
  )
  // Acknowledge that the user has viewed an abnormal death's detail, clearing
  // the "Deleted sessions" notification dot / row highlight. Persisted on the
  // deleted_sessions row so the mark is durable and shared across clients.
  .post(
    '/mark-death-seen',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      sessionId: z.string().min(1),
    })),
    async (c) => {
      const { projectSlug, sessionId } = c.req.valid('json')
      await recordDeathSeen(projectSlug, sessionId)
      return c.body(null, 204)
    },
  )
  // Pin (or unpin) a session to the sidebar's "Background" section. Takes an
  // explicit projectSlug (like /mark-death-seen) rather than resolving the
  // container: the target may be a deleted session with no pod to resolve.
  .post(
    '/set-background',
    zv('json', z.object({
      projectSlug: z.string().min(1),
      sessionId: z.string().min(1),
      background: z.boolean(),
    })),
    async (c) => {
      const { projectSlug, sessionId, background } = c.req.valid('json')
      await setSessionBackground(projectSlug, sessionId, background)
      // Push a fresh snapshot so the sidebar regroups immediately.
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  .post('/provisioning/:id/dismiss', (c) => {
    // Drop a provisioning entry (only meaningful for a failed one — successful
    // ones self-clean once the real session lists). Idempotent for any id.
    removeProvisioning(c.req.param('id'))
    return c.body(null, 204)
  })
  .post(
    '/:id/title',
    zv('json', z.object({ title: z.string().max(500) })),
    async (c) => {
      // Resolve in any state — renaming a waiting or just-stopped session is
      // fine; the title lives on the host, not in the container.
      const { projectSlug, sessionId } = await resolveSessionContainer(c.req.param('id'))
      await setSessionTitle(projectSlug, sessionId, c.req.valid('json').title)
      // Push a fresh snapshot so the sidebar reflects the rename immediately.
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  .get('/:id/terminals', async (c) => {
    const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await listSessionTerminals(jobName))
  })
  // The session's review diff — everything changed in the worktree since it
  // forked from the base branch (committed + working + untracked). An optional
  // `base` overrides the branch it's diffed against (fork point vs origin/<base>).
  .get(
    '/:id/changes',
    zv('query', z.object({ base: z.string().min(1).max(255).optional() })),
    async (c) => {
      const { jobName, sessionId, projectSlug } = await resolveSessionContainer(
        c.req.param('id'), { requireRunning: true },
      )
      // The branch the session forked from (its recorded upstream, e.g. main),
      // read host-side from the shared repo config — same source as the sidebar
      // base label. Passed as the DEFAULT diff base so committed work stays
      // visible even after the agent renames and pushes its branch, which makes
      // the current branch's own @{upstream} collapse the merge-base to HEAD.
      const forkBranch = await worktreeUpstreamBranch(
        repoDir(projectSlug), `agent/${sessionId}`,
      ).catch(() => null)
      return c.json(await getSessionChanges(jobName, c.req.valid('query').base, forkBranch ?? undefined))
    },
  )
  // Create a scratch-shell window in the session's `yaac` tmux session,
  // returning its entry so the client can open a pane immediately.
  .post('/:id/terminals', async (c) => {
    const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await createShellWindow(jobName))
  })
  .post(
    '/:id/terminals/close',
    zv('json', z.object({ target: z.string().min(1) })),
    async (c) => {
      const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      const { target } = c.req.valid('json')
      try {
        await killWindowTerminal(jobName, target)
      } catch (err) {
        throw new ServerError('VALIDATION', err instanceof Error ? err.message : String(err))
      }
      return c.body(null, 204)
    },
  )
  .get('/:id', async (c) => c.json(await getSessionDetail(c.req.param('id'))))
  .get('/:id/blocked-hosts', async (c) => c.json(await getSessionBlockedHosts(c.req.param('id'))))
  // Allow a previously-blocked host (webapp click-to-allow). The proxy prunes
  // the host from its recorded blocked set, so the snapshot we push clears the
  // badge. Persist/fan-out policy lives in allowSessionHost.
  .post(
    '/:id/allow-host',
    zv('json', z.object({
      // A bare hostname or wildcard pattern — the grammar hostMatchesPattern
      // (default-allowed-hosts.ts) matches against; no scheme/path/port.
      host: z.string().regex(/^[A-Za-z0-9*._-]+$/, 'host must be a bare hostname or *.wildcard pattern'),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      const { host, persist } = c.req.valid('json')
      const target = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      await allowSessionHost(target, host, { persist: persist ?? false })
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  // Forward a detected-but-unforwarded port (webapp click-to-forward). The
  // port must be in the session's surfaced unforwarded set — forwardSessionPort
  // rejects anything else, so the route can't be driven to open an arbitrary
  // port. Persist/fan-out policy lives in forwardSessionPort.
  .post(
    '/:id/forward-port',
    zv('json', z.object({
      containerPort: z.number().int().min(1).max(65535),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      const { containerPort, persist } = c.req.valid('json')
      const target = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      const mapping = await forwardSessionPort(target, containerPort, { persist: persist ?? false })
      // Fresh snapshot moves the port from unforwardedPorts into
      // forwardedPorts, self-clearing the popover row.
      notifySessionListChanged()
      return c.json(mapping)
    },
  )
  // Hide a detected port for this session (in-memory; resets with the server).
  // Same guard as forward-port: only a currently-surfaced port is
  // dismissable, so the dismissed set can't be grown arbitrarily.
  .post(
    '/:id/dismiss-port',
    zv('json', z.object({ containerPort: z.number().int().min(1).max(65535) })),
    async (c) => {
      const { containerPort } = c.req.valid('json')
      const target = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      if (!dismissSessionPort(target.sessionId, containerPort)) {
        throw new ServerError(
          'CONFLICT',
          `port ${containerPort} is not an unforwarded listener in session ${target.sessionId.slice(0, 8)}`,
        )
      }
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  .get('/:id/prompt', async (c) => {
    const prompt = await getSessionPrompt(c.req.param('id'))
    return c.json({ prompt: prompt ?? '' })
  })
